### ISSUE TITLE
Doesn't scale with display resolution, parts of UI inaccessible on displays less than 1080x1920

### ISSUE THREAD

**Issue by ZHDarkstar** [Meth962/FFX2SaveEditor#3]
![ss](https://user-images.githubusercontent.com/67379203/85576550-807dab80-b606-11ea-9c4d-8ea69d82aa0a.png)
When opened on displays less than 1080x1920, parts of the UI become inaccessible.

**Comment by Meth962** [comment]
Yep, sorry about that. I created it for 1080p+ resolutions since that's what resolution I was playing the game at.

**Comment by Vachne** [comment]
Meth, can you please address and fix this issue regarding resolution.  I really want to use this editor but my system does not support/allow for higher resolutions.  Thank you so much for your time and effort on this project as I am sure many people would be interested in using it!

**Comment by Meth962** [comment]
Hrm, this is my first and only WPF application so I’m not too good at figuring out how to scale everything automatically. I basically made it for 1920x1080 and it scales UP to 4K for me just fine. I guess it doesn’t go lower.

What is the resolution you are running at? I can try to make it work on lower resolutions.
1024x768?

Thank you for your email.

Meth

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Meth962** [comment]
Hey all, I tried to make the application scale and resize the Window. I'm not sure what it will show up as by default but you can now resize the window to make it fit (and presumably use maximize button) and it should now work for lower resolutions.

Open this ticket up if it still doesn't work for you!

https://github.com/Meth962/FFX2SaveEditor/releases/tag/v0.3
