### ISSUE TITLE
How to Open?

### ISSUE THREAD

**Issue by RunningManLKS** [Meth962/FFX2SaveEditor#4]
I downloaded v0.2 but as previously mentioned, part of it was inaccessible in lower resolutions. I downloaded the master file in the page but there's no application file. It said that the 1080 issue was fixed. How do you use it? Which file do you use?

**Comment by kiplripl** [comment]
Open FFX2SaveEditor.sln in VisualStudio and run. Running is the green arrow or Ctrl+F5.

**Comment by Meth962** [comment]
Hey guys, no longer need to build yourself. I started adding in releases where you can just download the EXE itself.

Thanks!
