### ISSUE TITLE
No Exe/APP file

### ISSUE THREAD

**Issue by nlegacion** [Meth962/FFX2SaveEditor#6]
when i downloaded it there's no Exe file or the save editor app it's all bunch of files etc etc but the save editor app si missing

**Comment by Vagente** [comment]
It's a visual studio project. You need to download visual studio and run it.

**Comment by Meth962** [comment]
Haha, that is not how Github works. You downloaded the source code. If you don't want/need the source code and just want the app, get it from the [releases](https://github.com/Meth962/FFX2SaveEditor/releases) instead (exe)
